spring.application.name=reservas
server.port=8080

# ==========================================================
# PostgreSQL (Base de Datos Local)
# ==========================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/reserva_salas_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
